---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: OpenFest dashboard

layout:
  - Development:
  - Social:
  - Bookmarks:

# This is the background image if you want to remove it just comment / remove the next few lines
background:
    image: https://www.openfest.org/2024//img/CoverOpenFest2024BG.webp
    blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    saturate: 20 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    brightness: 5 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
    opacity: 5 # 0-100

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
